//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiSolutionTest.ReservasWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reserva", Namespace="http://schemas.datacontract.org/2004/07/TaxiSolution.Dominio")]
    [System.SerializableAttribute()]
    public partial class Reserva : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaHoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDChoferField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDMedioPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaHora {
            get {
                return this.FechaHoraField;
            }
            set {
                if ((this.FechaHoraField.Equals(value) != true)) {
                    this.FechaHoraField = value;
                    this.RaisePropertyChanged("FechaHora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDChofer {
            get {
                return this.IDChoferField;
            }
            set {
                if ((this.IDChoferField.Equals(value) != true)) {
                    this.IDChoferField = value;
                    this.RaisePropertyChanged("IDChofer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDMedioPago {
            get {
                return this.IDMedioPagoField;
            }
            set {
                if ((this.IDMedioPagoField.Equals(value) != true)) {
                    this.IDMedioPagoField = value;
                    this.RaisePropertyChanged("IDMedioPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDUsuario {
            get {
                return this.IDUsuarioField;
            }
            set {
                if ((this.IDUsuarioField.Equals(value) != true)) {
                    this.IDUsuarioField = value;
                    this.RaisePropertyChanged("IDUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdministradorExcepciones", Namespace="http://schemas.datacontract.org/2004/07/TaxiSolution.Errores")]
    [System.SerializableAttribute()]
    public partial class AdministradorExcepciones : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReservasWS.IReservasService")]
    public interface IReservasService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservasService/CrearReserva", ReplyAction="http://tempuri.org/IReservasService/CrearReservaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TaxiSolutionTest.ReservasWS.AdministradorExcepciones), Action="http://tempuri.org/IReservasService/CrearReservaAdministradorExcepcionesFault", Name="AdministradorExcepciones", Namespace="http://schemas.datacontract.org/2004/07/TaxiSolution.Errores")]
        TaxiSolutionTest.ReservasWS.Reserva CrearReserva(TaxiSolutionTest.ReservasWS.Reserva reservaACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservasService/CrearReserva", ReplyAction="http://tempuri.org/IReservasService/CrearReservaResponse")]
        System.Threading.Tasks.Task<TaxiSolutionTest.ReservasWS.Reserva> CrearReservaAsync(TaxiSolutionTest.ReservasWS.Reserva reservaACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservasService/ObtenerReserva", ReplyAction="http://tempuri.org/IReservasService/ObtenerReservaResponse")]
        TaxiSolutionTest.ReservasWS.Reserva ObtenerReserva(TaxiSolutionTest.ReservasWS.Reserva reservaAObtener);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservasService/ObtenerReserva", ReplyAction="http://tempuri.org/IReservasService/ObtenerReservaResponse")]
        System.Threading.Tasks.Task<TaxiSolutionTest.ReservasWS.Reserva> ObtenerReservaAsync(TaxiSolutionTest.ReservasWS.Reserva reservaAObtener);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservasService/ModificarReserva", ReplyAction="http://tempuri.org/IReservasService/ModificarReservaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TaxiSolutionTest.ReservasWS.AdministradorExcepciones), Action="http://tempuri.org/IReservasService/ModificarReservaAdministradorExcepcionesFault" +
            "", Name="AdministradorExcepciones", Namespace="http://schemas.datacontract.org/2004/07/TaxiSolution.Errores")]
        TaxiSolutionTest.ReservasWS.Reserva ModificarReserva(TaxiSolutionTest.ReservasWS.Reserva reservaAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservasService/ModificarReserva", ReplyAction="http://tempuri.org/IReservasService/ModificarReservaResponse")]
        System.Threading.Tasks.Task<TaxiSolutionTest.ReservasWS.Reserva> ModificarReservaAsync(TaxiSolutionTest.ReservasWS.Reserva reservaAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservasService/EliminarReserva", ReplyAction="http://tempuri.org/IReservasService/EliminarReservaResponse")]
        void EliminarReserva(TaxiSolutionTest.ReservasWS.Reserva reservaAEliminar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservasService/EliminarReserva", ReplyAction="http://tempuri.org/IReservasService/EliminarReservaResponse")]
        System.Threading.Tasks.Task EliminarReservaAsync(TaxiSolutionTest.ReservasWS.Reserva reservaAEliminar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservasService/ListarReserva", ReplyAction="http://tempuri.org/IReservasService/ListarReservaResponse")]
        System.Collections.Generic.List<TaxiSolutionTest.ReservasWS.Reserva> ListarReserva();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservasService/ListarReserva", ReplyAction="http://tempuri.org/IReservasService/ListarReservaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TaxiSolutionTest.ReservasWS.Reserva>> ListarReservaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReservasServiceChannel : TaxiSolutionTest.ReservasWS.IReservasService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservasServiceClient : System.ServiceModel.ClientBase<TaxiSolutionTest.ReservasWS.IReservasService>, TaxiSolutionTest.ReservasWS.IReservasService {
        
        public ReservasServiceClient() {
        }
        
        public ReservasServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservasServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservasServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservasServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TaxiSolutionTest.ReservasWS.Reserva CrearReserva(TaxiSolutionTest.ReservasWS.Reserva reservaACrear) {
            return base.Channel.CrearReserva(reservaACrear);
        }
        
        public System.Threading.Tasks.Task<TaxiSolutionTest.ReservasWS.Reserva> CrearReservaAsync(TaxiSolutionTest.ReservasWS.Reserva reservaACrear) {
            return base.Channel.CrearReservaAsync(reservaACrear);
        }
        
        public TaxiSolutionTest.ReservasWS.Reserva ObtenerReserva(TaxiSolutionTest.ReservasWS.Reserva reservaAObtener) {
            return base.Channel.ObtenerReserva(reservaAObtener);
        }
        
        public System.Threading.Tasks.Task<TaxiSolutionTest.ReservasWS.Reserva> ObtenerReservaAsync(TaxiSolutionTest.ReservasWS.Reserva reservaAObtener) {
            return base.Channel.ObtenerReservaAsync(reservaAObtener);
        }
        
        public TaxiSolutionTest.ReservasWS.Reserva ModificarReserva(TaxiSolutionTest.ReservasWS.Reserva reservaAModificar) {
            return base.Channel.ModificarReserva(reservaAModificar);
        }
        
        public System.Threading.Tasks.Task<TaxiSolutionTest.ReservasWS.Reserva> ModificarReservaAsync(TaxiSolutionTest.ReservasWS.Reserva reservaAModificar) {
            return base.Channel.ModificarReservaAsync(reservaAModificar);
        }
        
        public void EliminarReserva(TaxiSolutionTest.ReservasWS.Reserva reservaAEliminar) {
            base.Channel.EliminarReserva(reservaAEliminar);
        }
        
        public System.Threading.Tasks.Task EliminarReservaAsync(TaxiSolutionTest.ReservasWS.Reserva reservaAEliminar) {
            return base.Channel.EliminarReservaAsync(reservaAEliminar);
        }
        
        public System.Collections.Generic.List<TaxiSolutionTest.ReservasWS.Reserva> ListarReserva() {
            return base.Channel.ListarReserva();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TaxiSolutionTest.ReservasWS.Reserva>> ListarReservaAsync() {
            return base.Channel.ListarReservaAsync();
        }
    }
}
